helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/github-pr-slack-notifier
    forcestring: true
  - name: image.tag
    value: main@sha256:4b3d8bec25e3758117a0370709124a40a1ab4f9ffa2eb8d0a43a90d6766e80c2
    forcestring: true
