replicaCount: 1

image:
  repository: ghcr.io/mvs5465-test/github-pr-slack-notifier
  tag: "main"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  GITHUB_APP_ID: ""
  GITHUB_INSTALLATION_IDS: ""
  POLL_INTERVAL_SECONDS: "30"
  DRY_RUN: "true"
  ROUTES_JSON: "[]"

secretEnv:
  name: "github-pr-slack-notifier-secret"
  githubAppPrivateKeyKey: "GITHUB_APP_PRIVATE_KEY"
  slackBotTokenKey: "SLACK_BOT_TOKEN"

nodeSelector: {}
tolerations: []
affinity: {}
